<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
    <Content Remove="wwwroot\LOGO FINAL.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\Images\LOGO FINAL.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
  </ItemGroup>

	<ItemGroup>
		<UpToDateCheckBuilt Include="wwwroot/css/site.css" Set="Css" />
		<UpToDateCheckBuilt Include="tailwind.config.js" Set="Css" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
	  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
	</ItemGroup>

	<Target Name="Tailwind" BeforeTargets="Build">
		<Exec Command="npm run css:build" />
	</Target>

</Project>
